// flow-typed signature: e85a840886c4c445a0e0d1b1c1b20fef
// flow-typed version: <<STUB>>/@types/three_v^0.93.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/three'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/three' {
  declare module.exports: any;
}
