// @flow

const buildCDNUrl = (path: string) => `https://static.odycdn.com/emoticons/${path}`;

const buildEmote = (name: string, path: string) => ({
  name: __(`:${name}:`),
  url: buildCDNUrl(path),
});

const getEmotes = (px: string, multiplier: string) => [
  buildEmote('ALIEN', `${px}/Alien${multiplier}.png`),
  buildEmote('ANGRY_2', `${px}/angry%202${multiplier}.png`),
  buildEmote('ANGRY_3', `${px}/angry%203${multiplier}.png`),
  buildEmote('ANGRY_4', `${px}/angry%204${multiplier}.png`),
  buildEmote('ANGRY_1', `${px}/angry${multiplier}.png`),
  buildEmote('BLIND', `${px}/blind${multiplier}.png`),
  buildEmote('BLOCK', `${px}/block${multiplier}.png`),
  buildEmote('BOMB', `${px}/bomb${multiplier}.png`),
  buildEmote('BRAIN_CHIP', `${px}/Brain%20chip${multiplier}.png`),
  buildEmote('CONFIRM', `${px}/CONFIRM${multiplier}.png`),
  buildEmote('CONFUSED_1', `${px}/confused-1${multiplier}.png`),
  buildEmote('CONFUSED_2', `${px}/confused${multiplier}.png`),
  buildEmote('COOKING_SOMETHING_NICE', `${px}/cooking%20something%20nice${multiplier}.png`),
  buildEmote('CRY_2', `${px}/cry%202${multiplier}.png`),
  buildEmote('CRY_3', `${px}/cry%203${multiplier}.png`),
  buildEmote('CRY_4', `${px}/cry%204${multiplier}.png`),
  buildEmote('CRY_5', `${px}/cry%205${multiplier}.png`),
  buildEmote('CRY_1', `${px}/cry${multiplier}.png`),
  buildEmote('SPACE_DOGE', `${px}/doge${multiplier}.png`),
  buildEmote('DONUT', `${px}/donut${multiplier}.png`),
  buildEmote('EGGPLANT_WITH_CONDOM', `${px}/eggplant%20with%20condom${multiplier}.png`),
  buildEmote('EGGPLANT', `${px}/eggplant${multiplier}.png`),
  buildEmote('FIRE_UP', `${px}/fire%20up${multiplier}.png`),
  buildEmote('FLAT_EARTH', `${px}/Flat%20earth${multiplier}.png`),
  buildEmote('FLYING_SAUCER', `${px}/Flying%20saucer${multiplier}.png`),
  buildEmote('HEART_CHOPPER', `${px}/heart%20chopper${multiplier}.png`),
  buildEmote('HYPER_TROLL', `${px}/HyperTroll${multiplier}.png`),
  buildEmote('ICE_CREAM', `${px}/ice%20cream${multiplier}.png`),
  buildEmote('IDK', `${px}/IDK${multiplier}.png`),
  buildEmote('ILLUMINATI_1', `${px}/Illuminati-1${multiplier}.png`),
  buildEmote('ILLUMINATI_2', `${px}/Illuminati${multiplier}.png`),
  buildEmote('KISS_2', `${px}/kiss%202${multiplier}.png`),
  buildEmote('KISS_1', `${px}/kiss${multiplier}.png`),
  buildEmote('LASER_GUN', `${px}/laser%20gun${multiplier}.png`),
  buildEmote('LAUGHING_2', `${px}/Laughing 2${multiplier}.png`),
  buildEmote('LAUGHING_1', `${px}/Laughing${multiplier}.png`),
  buildEmote('LOLLIPOP', `${px}/Lollipop${multiplier}.png`),
  buildEmote('LOVE_2', `${px}/Love%202${multiplier}.png`),
  buildEmote('LOVE_1', `${px}/Love${multiplier}.png`),
  buildEmote('MONSTER', `${px}/Monster${multiplier}.png`),
  buildEmote('MUSHROOM', `${px}/mushroom${multiplier}.png`),
  buildEmote('NAIL_IT', `${px}/Nail%20It${multiplier}.png`),
  buildEmote('NO', `${px}/NO${multiplier}.png`),
  buildEmote('OUCH', `${px}/ouch${multiplier}.png`),
  buildEmote('PREACE', `${px}/peace${multiplier}.png`),
  buildEmote('PIZZA', `${px}/pizza${multiplier}.png`),
  buildEmote('RABBIT_HOLE', `${px}/rabbit%20hole${multiplier}.png`),
  buildEmote('RAINBOW_PUKE_1', `${px}/rainbow%20puke-1${multiplier}.png`),
  buildEmote('RAINBOW_PUKE_2', `${px}/rainbow%20puke${multiplier}.png`),
  buildEmote('SPACE_RESITAS', `${px}/resitas${multiplier}.png`),
  buildEmote('ROCK', `${px}/ROCK${multiplier}.png`),
  buildEmote('SAD', `${px}/sad${multiplier}.png`),
  buildEmote('SALTY', `${px}/salty${multiplier}.png`),
  buildEmote('SCARY', `${px}/scary${multiplier}.png`),
  buildEmote('SLEEP', `${px}/Sleep${multiplier}.png`),
  buildEmote('SLIME_DOWN', `${px}/slime%20down${multiplier}.png`),
  buildEmote('SMELLY_SOCKS', `${px}/smelly%20socks${multiplier}.png`),
  buildEmote('SMILE_2', `${px}/smile%202${multiplier}.png`),
  buildEmote('SMILE_1', `${px}/smile${multiplier}.png`),
  buildEmote('SPACE_CHAD', `${px}/space%20chad${multiplier}.png`),
  buildEmote('SPACE_JULIAN', `${px}/Space%20Julian${multiplier}.png`),
  buildEmote('SPACE_TOM', `${px}/space%20Tom${multiplier}.png`),
  buildEmote('SPACE_GREEN_WOJAK', `${px}/space%20wojak-1${multiplier}.png`),
  buildEmote('SPACE_RED_WOJAK', `${px}/space%20wojak${multiplier}.png`),
  buildEmote('SPOCK', `${px}/SPOCK${multiplier}.png`),
  buildEmote('STAR', `${px}/Star${multiplier}.png`),
  buildEmote('SUNNY_DAY', `${px}/sunny%20day${multiplier}.png`),
  buildEmote('SUPRISED', `${px}/surprised${multiplier}.png`),
  buildEmote('SWEET', `${px}/sweet${multiplier}.png`),
  buildEmote('THINKING_1', `${px}/thinking-1${multiplier}.png`),
  buildEmote('THINKING_2', `${px}/thinking${multiplier}.png`),
  buildEmote('THUMB_DOWN', `${px}/thumb%20down${multiplier}.png`),
  buildEmote('THUMB_UP_1', `${px}/thumb%20up-1${multiplier}.png`),
  buildEmote('THUMB_UP_2', `${px}/thumb%20up${multiplier}.png`),
  buildEmote('TINFOIL_HAT', `${px}/tin%20hat${multiplier}.png`),
  buildEmote('TROLL_KING', `${px}/Troll%20king${multiplier}.png`),
  buildEmote('UFO', `${px}/ufo${multiplier}.png`),
  buildEmote('WAITING', `${px}/waiting${multiplier}.png`),
  buildEmote('WHAT', `${px}/what_${multiplier}.png`),
  buildEmote('WOODOO_DOLL', `${px}/woodo%20doll${multiplier}.png`),
];

export const EMOTES_24px = getEmotes('24%20px', '');
export const EMOTES_36px = getEmotes('36px', '@1.5x');
export const EMOTES_48px = getEmotes('48%20px', '@2x');
export const EMOTES_72px = getEmotes('72%20px', '@3x');
