// Customer-facing title for a page.
//
// Primarily used for the browser tab and history title.
// Ensure new strings are added to 'app-string.json' for localization.

import * as PAGES from 'constants/pages';

export const PAGE_TITLE = {
  // --- Categories ---
  [PAGES.CREATIVE_ARTS]: 'The Arts',
  [PAGES.DISCOVER]: 'Wild West',
  [PAGES.EDUCATION]: 'Education',
  [PAGES.ENLIGHTENMENT]: 'Enlightenment',
  [PAGES.FEATURED]: 'Featured',
  [PAGES.FINANCE]: 'Finance 2.0',
  [PAGES.GAMING]: 'Gaming',
  [PAGES.GENERAL]: 'Cheese',
  [PAGES.LAB]: 'Lab',
  [PAGES.MOVIES]: 'Movies',
  [PAGES.MUSIC]: 'Music',
  [PAGES.NEWS]: 'News & Politics',
  [PAGES.POP_CULTURE]: 'Pop Culture',
  [PAGES.TECH]: 'Tech',
  [PAGES.UNIVERSE]: 'Universe',
  [PAGES.WILD_WEST]: 'Wild West',

  // --- Everything else in alphabetical order ---
  [PAGES.BUY]: 'Buy or Swap',
  [PAGES.CHANNELS]: 'Your channels',
  [PAGES.CHANNELS_FOLLOWING]: 'Following',
  [PAGES.CHANNELS_FOLLOWING_DISCOVER]: 'Discover Channels',
  [PAGES.CHANNEL_NEW]: 'Create a channel',
  [PAGES.CHECKOUT]: 'Checkout',
  [PAGES.CODE_2257]: '2257',
  [PAGES.PRIVACY_POLICY]: 'Privacy Policy',
  [PAGES.TOS]: 'Terms of Service',
  [PAGES.YOUTUBE_TOS]: 'YouTube Sync Terms of Service',
  [PAGES.CREATOR_DASHBOARD]: 'Creator Analytics',
  [PAGES.HELP]: 'Help',
  [PAGES.INVITE]: 'Invite',
  [PAGES.LISTS]: 'Lists',
  [PAGES.LIVESTREAM]: 'Go Live on Odysee',
  [PAGES.LIVESTREAM_CURRENT]: 'Live (Experimental)',
  [PAGES.NOTIFICATIONS]: 'Notifications',
  [PAGES.RECEIVE]: 'Your address',
  [PAGES.REPORT]: 'Report an issue or request a feature',
  [PAGES.REPORT_CONTENT]: 'Report content',
  [PAGES.REPOST_NEW]: 'Repost',
  [PAGES.REWARDS]: 'Rewards',
  [PAGES.REWARDS_VERIFY]: 'Verify to earn Credits',
  [PAGES.SEARCH]: 'Search',
  [PAGES.SEND]: 'Send Credits',
  [PAGES.SETTINGS]: 'Settings',
  [PAGES.SETTINGS_BLOCKED_MUTED]: 'Blocked and muted channels',
  [PAGES.SETTINGS_CREATOR]: 'Creator settings',
  [PAGES.SETTINGS_NOTIFICATIONS]: 'Manage notifications',
  [PAGES.SETTINGS_STRIPE_ACCOUNT]: 'Bank Accounts',
  [PAGES.SETTINGS_STRIPE_CARD]: 'Payment Methods',
  [PAGES.SETTINGS_UPDATE_PWD]: 'Update password',
  [PAGES.SETTINGS_OWN_COMMENTS]: 'Your comments',
  [PAGES.SWAP]: 'Swap Credits',
  [PAGES.TAGS_FOLLOWING]: 'Tags',
  [PAGES.TAGS_FOLLOWING_MANAGE]: 'Manage tags',
  [PAGES.UPLOAD]: 'Upload',
  [PAGES.UPLOADS]: 'Your uploads',
  [PAGES.WALLET]: 'Wallet',
  [PAGES.WELCOME]: 'Welcome',
  [PAGES.YOUTUBE_SYNC]: 'YouTube Sync',
};
