const SUPPORTED_BROWSER_LANGUAGES = {
  en: 'en',
  da: 'da',
  'zh-CN': 'zh-Hans',
  'zh-TW': 'zh-Hant',
  'zh-Hans': 'zh-Hans',
  'zh-Hant': 'zh-Hant',
  hr: 'hr',
  nl: 'nl',
  fr: 'fr',
  de: 'de',
  gu: 'gu',
  hi: 'hi',
  id: 'id',
  jv: 'jv',
  it: 'it',
  ms: 'ms',
  ml: 'ml',
  mr: 'mr',
  pa: 'pa',
  pl: 'pl',
  pt: 'pt',
  ro: 'ro',
  ru: 'ru',
  sr: 'sr',
  sk: 'sk',
  ur: 'ur',
  ca: 'ca',
  es: 'es',
  sv: 'sv',
  tr: 'tr',
  cs: 'cs',
  kn: 'kn',
  uk: 'uk',
};

// Properties: language code (e.g. 'ja')
// Values: name of the language in native form (e.g. '日本語')
export default SUPPORTED_BROWSER_LANGUAGES;
