// flow-typed signature: 0179aaf62abe5de0fea307e93b07f0fd
// flow-typed version: <<STUB>>/async-exit-hook_v^2.0.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'async-exit-hook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'async-exit-hook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'async-exit-hook/index' {
  declare module.exports: $Exports<'async-exit-hook'>;
}
declare module 'async-exit-hook/index.js' {
  declare module.exports: $Exports<'async-exit-hook'>;
}
