// flow-typed signature: 9ac14a1f40af643c7a1cda684c6d14c6
// flow-typed version: <<STUB>>/country-data_v^0.0.31/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'country-data'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'country-data' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'country-data/data/continents' {
  declare module.exports: any;
}

declare module 'country-data/data/country_csv_to_json' {
  declare module.exports: any;
}

declare module 'country-data/data/currency_csv_to_json' {
  declare module.exports: any;
}

declare module 'country-data/data/language_csv_to_json' {
  declare module.exports: any;
}

declare module 'country-data/data/normalize_csv' {
  declare module.exports: any;
}

declare module 'country-data/data/regions' {
  declare module.exports: any;
}

declare module 'country-data/lookup' {
  declare module.exports: any;
}

declare module 'country-data/test/calling-codes' {
  declare module.exports: any;
}

declare module 'country-data/test/countries' {
  declare module.exports: any;
}

declare module 'country-data/test/cross-references' {
  declare module.exports: any;
}

declare module 'country-data/test/currencies' {
  declare module.exports: any;
}

declare module 'country-data/test/languages' {
  declare module.exports: any;
}

declare module 'country-data/test/lookup' {
  declare module.exports: any;
}

declare module 'country-data/test/regions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'country-data/data/continents.js' {
  declare module.exports: $Exports<'country-data/data/continents'>;
}
declare module 'country-data/data/country_csv_to_json.js' {
  declare module.exports: $Exports<'country-data/data/country_csv_to_json'>;
}
declare module 'country-data/data/currency_csv_to_json.js' {
  declare module.exports: $Exports<'country-data/data/currency_csv_to_json'>;
}
declare module 'country-data/data/language_csv_to_json.js' {
  declare module.exports: $Exports<'country-data/data/language_csv_to_json'>;
}
declare module 'country-data/data/normalize_csv.js' {
  declare module.exports: $Exports<'country-data/data/normalize_csv'>;
}
declare module 'country-data/data/regions.js' {
  declare module.exports: $Exports<'country-data/data/regions'>;
}
declare module 'country-data/index' {
  declare module.exports: $Exports<'country-data'>;
}
declare module 'country-data/index.js' {
  declare module.exports: $Exports<'country-data'>;
}
declare module 'country-data/lookup.js' {
  declare module.exports: $Exports<'country-data/lookup'>;
}
declare module 'country-data/test/calling-codes.js' {
  declare module.exports: $Exports<'country-data/test/calling-codes'>;
}
declare module 'country-data/test/countries.js' {
  declare module.exports: $Exports<'country-data/test/countries'>;
}
declare module 'country-data/test/cross-references.js' {
  declare module.exports: $Exports<'country-data/test/cross-references'>;
}
declare module 'country-data/test/currencies.js' {
  declare module.exports: $Exports<'country-data/test/currencies'>;
}
declare module 'country-data/test/languages.js' {
  declare module.exports: $Exports<'country-data/test/languages'>;
}
declare module 'country-data/test/lookup.js' {
  declare module.exports: $Exports<'country-data/test/lookup'>;
}
declare module 'country-data/test/regions.js' {
  declare module.exports: $Exports<'country-data/test/regions'>;
}
