// flow-typed signature: 4c1b3e9c5881b71f8fa1de27757c7fab
// flow-typed version: <<STUB>>/css-loader_v^2.1.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'css-loader/dist/CssSyntaxError' {
  declare module.exports: any;
}

declare module 'css-loader/dist/index' {
  declare module.exports: any;
}

declare module 'css-loader/dist/plugins/index' {
  declare module.exports: any;
}

declare module 'css-loader/dist/plugins/postcss-icss-parser' {
  declare module.exports: any;
}

declare module 'css-loader/dist/plugins/postcss-import-parser' {
  declare module.exports: any;
}

declare module 'css-loader/dist/plugins/postcss-url-parser' {
  declare module.exports: any;
}

declare module 'css-loader/dist/runtime/api' {
  declare module.exports: any;
}

declare module 'css-loader/dist/runtime/url-escape' {
  declare module.exports: any;
}

declare module 'css-loader/dist/utils' {
  declare module.exports: any;
}

declare module 'css-loader/dist/Warning' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-loader/dist/cjs.js' {
  declare module.exports: $Exports<'css-loader/dist/cjs'>;
}
declare module 'css-loader/dist/CssSyntaxError.js' {
  declare module.exports: $Exports<'css-loader/dist/CssSyntaxError'>;
}
declare module 'css-loader/dist/index.js' {
  declare module.exports: $Exports<'css-loader/dist/index'>;
}
declare module 'css-loader/dist/plugins/index.js' {
  declare module.exports: $Exports<'css-loader/dist/plugins/index'>;
}
declare module 'css-loader/dist/plugins/postcss-icss-parser.js' {
  declare module.exports: $Exports<'css-loader/dist/plugins/postcss-icss-parser'>;
}
declare module 'css-loader/dist/plugins/postcss-import-parser.js' {
  declare module.exports: $Exports<'css-loader/dist/plugins/postcss-import-parser'>;
}
declare module 'css-loader/dist/plugins/postcss-url-parser.js' {
  declare module.exports: $Exports<'css-loader/dist/plugins/postcss-url-parser'>;
}
declare module 'css-loader/dist/runtime/api.js' {
  declare module.exports: $Exports<'css-loader/dist/runtime/api'>;
}
declare module 'css-loader/dist/runtime/url-escape.js' {
  declare module.exports: $Exports<'css-loader/dist/runtime/url-escape'>;
}
declare module 'css-loader/dist/utils.js' {
  declare module.exports: $Exports<'css-loader/dist/utils'>;
}
declare module 'css-loader/dist/Warning.js' {
  declare module.exports: $Exports<'css-loader/dist/Warning'>;
}
