// flow-typed signature: de6eecdb020f5cf0c91faf3cf35d53bf
// flow-typed version: <<STUB>>/dat.gui_v^0.7.2/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dat.gui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dat.gui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dat.gui/build/dat.gui' {
  declare module.exports: any;
}

declare module 'dat.gui/build/dat.gui.min' {
  declare module.exports: any;
}

declare module 'dat.gui/build/dat.gui.module' {
  declare module.exports: any;
}

declare module 'dat.gui/rollup.config' {
  declare module.exports: any;
}

declare module 'dat.gui/rollup.config.min' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/color/Color' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/color/interpret' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/color/math' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/color/toString' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/controllers/BooleanController' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/controllers/ColorController' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/controllers/Controller' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/controllers/ControllerFactory' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/controllers/FunctionController' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/controllers/NumberController' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/controllers/NumberControllerBox' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/controllers/NumberControllerSlider' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/controllers/OptionController' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/controllers/StringController' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/dom/CenteredDiv' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/dom/dom' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/gui/GUI' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/gui/saveDialogue.html' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/index' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/utils/common' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/utils/css' {
  declare module.exports: any;
}

declare module 'dat.gui/src/dat/utils/requestAnimationFrame' {
  declare module.exports: any;
}

declare module 'dat.gui/tests/jquery' {
  declare module.exports: any;
}

declare module 'dat.gui/tests/qunit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dat.gui/build/dat.gui.js' {
  declare module.exports: $Exports<'dat.gui/build/dat.gui'>;
}
declare module 'dat.gui/build/dat.gui.min.js' {
  declare module.exports: $Exports<'dat.gui/build/dat.gui.min'>;
}
declare module 'dat.gui/build/dat.gui.module.js' {
  declare module.exports: $Exports<'dat.gui/build/dat.gui.module'>;
}
declare module 'dat.gui/rollup.config.js' {
  declare module.exports: $Exports<'dat.gui/rollup.config'>;
}
declare module 'dat.gui/rollup.config.min.js' {
  declare module.exports: $Exports<'dat.gui/rollup.config.min'>;
}
declare module 'dat.gui/src/dat/color/Color.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/color/Color'>;
}
declare module 'dat.gui/src/dat/color/interpret.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/color/interpret'>;
}
declare module 'dat.gui/src/dat/color/math.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/color/math'>;
}
declare module 'dat.gui/src/dat/color/toString.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/color/toString'>;
}
declare module 'dat.gui/src/dat/controllers/BooleanController.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/controllers/BooleanController'>;
}
declare module 'dat.gui/src/dat/controllers/ColorController.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/controllers/ColorController'>;
}
declare module 'dat.gui/src/dat/controllers/Controller.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/controllers/Controller'>;
}
declare module 'dat.gui/src/dat/controllers/ControllerFactory.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/controllers/ControllerFactory'>;
}
declare module 'dat.gui/src/dat/controllers/FunctionController.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/controllers/FunctionController'>;
}
declare module 'dat.gui/src/dat/controllers/NumberController.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/controllers/NumberController'>;
}
declare module 'dat.gui/src/dat/controllers/NumberControllerBox.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/controllers/NumberControllerBox'>;
}
declare module 'dat.gui/src/dat/controllers/NumberControllerSlider.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/controllers/NumberControllerSlider'>;
}
declare module 'dat.gui/src/dat/controllers/OptionController.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/controllers/OptionController'>;
}
declare module 'dat.gui/src/dat/controllers/StringController.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/controllers/StringController'>;
}
declare module 'dat.gui/src/dat/dom/CenteredDiv.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/dom/CenteredDiv'>;
}
declare module 'dat.gui/src/dat/dom/dom.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/dom/dom'>;
}
declare module 'dat.gui/src/dat/gui/GUI.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/gui/GUI'>;
}
declare module 'dat.gui/src/dat/gui/saveDialogue.html.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/gui/saveDialogue.html'>;
}
declare module 'dat.gui/src/dat/index.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/index'>;
}
declare module 'dat.gui/src/dat/utils/common.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/utils/common'>;
}
declare module 'dat.gui/src/dat/utils/css.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/utils/css'>;
}
declare module 'dat.gui/src/dat/utils/requestAnimationFrame.js' {
  declare module.exports: $Exports<'dat.gui/src/dat/utils/requestAnimationFrame'>;
}
declare module 'dat.gui/tests/jquery.js' {
  declare module.exports: $Exports<'dat.gui/tests/jquery'>;
}
declare module 'dat.gui/tests/qunit.js' {
  declare module.exports: $Exports<'dat.gui/tests/qunit'>;
}
