// flow-typed signature: 3c0ff501d98f81d7c038268edb616ce8
// flow-typed version: <<STUB>>/dom-scroll-into-view_v^1.2.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dom-scroll-into-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dom-scroll-into-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dom-scroll-into-view/lib/dom-scroll-into-view' {
  declare module.exports: any;
}

declare module 'dom-scroll-into-view/lib/index' {
  declare module.exports: any;
}

declare module 'dom-scroll-into-view/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dom-scroll-into-view/lib/dom-scroll-into-view.js' {
  declare module.exports: $Exports<'dom-scroll-into-view/lib/dom-scroll-into-view'>;
}
declare module 'dom-scroll-into-view/lib/index.js' {
  declare module.exports: $Exports<'dom-scroll-into-view/lib/index'>;
}
declare module 'dom-scroll-into-view/lib/util.js' {
  declare module.exports: $Exports<'dom-scroll-into-view/lib/util'>;
}
