// flow-typed signature: fb956bb4623bc969695376edde76eb27
// flow-typed version: <<STUB>>/electron-builder_v^20.38.4/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-builder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-builder' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-builder/out/builder' {
  declare module.exports: any;
}

declare module 'electron-builder/out/cli/cli' {
  declare module.exports: any;
}

declare module 'electron-builder/out/cli/create-self-signed-cert' {
  declare module.exports: any;
}

declare module 'electron-builder/out/cli/install-app-deps' {
  declare module.exports: any;
}

declare module 'electron-builder/out/cli/start' {
  declare module.exports: any;
}

declare module 'electron-builder/out/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-builder/out/builder.js' {
  declare module.exports: $Exports<'electron-builder/out/builder'>;
}
declare module 'electron-builder/out/cli/cli.js' {
  declare module.exports: $Exports<'electron-builder/out/cli/cli'>;
}
declare module 'electron-builder/out/cli/create-self-signed-cert.js' {
  declare module.exports: $Exports<'electron-builder/out/cli/create-self-signed-cert'>;
}
declare module 'electron-builder/out/cli/install-app-deps.js' {
  declare module.exports: $Exports<'electron-builder/out/cli/install-app-deps'>;
}
declare module 'electron-builder/out/cli/start.js' {
  declare module.exports: $Exports<'electron-builder/out/cli/start'>;
}
declare module 'electron-builder/out/index.js' {
  declare module.exports: $Exports<'electron-builder/out/index'>;
}
