// flow-typed signature: bc2488f144e2cdd85f8de1a45a3dbaf2
// flow-typed version: <<STUB>>/electron-publisher-s3_v^20.8.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-publisher-s3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-publisher-s3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-publisher-s3/out/BaseS3Publisher' {
  declare module.exports: any;
}

declare module 'electron-publisher-s3/out/s3Publisher' {
  declare module.exports: any;
}

declare module 'electron-publisher-s3/out/spacesPublisher' {
  declare module.exports: any;
}

declare module 'electron-publisher-s3/out/uploader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-publisher-s3/out/BaseS3Publisher.js' {
  declare module.exports: $Exports<'electron-publisher-s3/out/BaseS3Publisher'>;
}
declare module 'electron-publisher-s3/out/s3Publisher.js' {
  declare module.exports: $Exports<'electron-publisher-s3/out/s3Publisher'>;
}
declare module 'electron-publisher-s3/out/spacesPublisher.js' {
  declare module.exports: $Exports<'electron-publisher-s3/out/spacesPublisher'>;
}
declare module 'electron-publisher-s3/out/uploader.js' {
  declare module.exports: $Exports<'electron-publisher-s3/out/uploader'>;
}
