// flow-typed signature: f4252f9600f889c2eb6300501f46c0f1
// flow-typed version: <<STUB>>/electron-window-state_v^4.1.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-window-state'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-window-state' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'electron-window-state/index' {
  declare module.exports: $Exports<'electron-window-state'>;
}
declare module 'electron-window-state/index.js' {
  declare module.exports: $Exports<'electron-window-state'>;
}
