// flow-typed signature: b2525aab5150a9b02d85d0d46aa3572c
// flow-typed version: <<STUB>>/electron-webpack_v^2.6.2/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-webpack/out/cli' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/config' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/configurators/dll' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/configurators/eslint' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/configurators/js' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/configurators/ts' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/configurators/vue/vue-main-dev-entry' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/configurators/vue/vue' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/core' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/dev/ChildProcessManager' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/dev/dev-runner' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/dev/devUtil' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/dev/WebpackDevServerManager' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/electron-builder' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/electron-main-hmr/HmrClient' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/electron-main-hmr/HmrServer' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/electron-main-hmr/main-hmr' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/main' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/plugins/WatchMatchPlugin' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/plugins/WebpackRemoveOldAssetsPlugin' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/targets/BaseTarget' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/targets/MainTarget' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/targets/RendererTarget' {
  declare module.exports: any;
}

declare module 'electron-webpack/out/util' {
  declare module.exports: any;
}

declare module 'electron-webpack/vue-renderer-entry' {
  declare module.exports: any;
}

declare module 'electron-webpack/webpack.app.config' {
  declare module.exports: any;
}

declare module 'electron-webpack/webpack.main.config' {
  declare module.exports: any;
}

declare module 'electron-webpack/webpack.renderer.config' {
  declare module.exports: any;
}

declare module 'electron-webpack/webpack.renderer.dll.config' {
  declare module.exports: any;
}

declare module 'electron-webpack/webpack.test.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-webpack/out/cli.js' {
  declare module.exports: $Exports<'electron-webpack/out/cli'>;
}
declare module 'electron-webpack/out/config.js' {
  declare module.exports: $Exports<'electron-webpack/out/config'>;
}
declare module 'electron-webpack/out/configurators/dll.js' {
  declare module.exports: $Exports<'electron-webpack/out/configurators/dll'>;
}
declare module 'electron-webpack/out/configurators/eslint.js' {
  declare module.exports: $Exports<'electron-webpack/out/configurators/eslint'>;
}
declare module 'electron-webpack/out/configurators/js.js' {
  declare module.exports: $Exports<'electron-webpack/out/configurators/js'>;
}
declare module 'electron-webpack/out/configurators/ts.js' {
  declare module.exports: $Exports<'electron-webpack/out/configurators/ts'>;
}
declare module 'electron-webpack/out/configurators/vue/vue-main-dev-entry.js' {
  declare module.exports: $Exports<'electron-webpack/out/configurators/vue/vue-main-dev-entry'>;
}
declare module 'electron-webpack/out/configurators/vue/vue.js' {
  declare module.exports: $Exports<'electron-webpack/out/configurators/vue/vue'>;
}
declare module 'electron-webpack/out/core.js' {
  declare module.exports: $Exports<'electron-webpack/out/core'>;
}
declare module 'electron-webpack/out/dev/ChildProcessManager.js' {
  declare module.exports: $Exports<'electron-webpack/out/dev/ChildProcessManager'>;
}
declare module 'electron-webpack/out/dev/dev-runner.js' {
  declare module.exports: $Exports<'electron-webpack/out/dev/dev-runner'>;
}
declare module 'electron-webpack/out/dev/devUtil.js' {
  declare module.exports: $Exports<'electron-webpack/out/dev/devUtil'>;
}
declare module 'electron-webpack/out/dev/WebpackDevServerManager.js' {
  declare module.exports: $Exports<'electron-webpack/out/dev/WebpackDevServerManager'>;
}
declare module 'electron-webpack/out/electron-builder.js' {
  declare module.exports: $Exports<'electron-webpack/out/electron-builder'>;
}
declare module 'electron-webpack/out/electron-main-hmr/HmrClient.js' {
  declare module.exports: $Exports<'electron-webpack/out/electron-main-hmr/HmrClient'>;
}
declare module 'electron-webpack/out/electron-main-hmr/HmrServer.js' {
  declare module.exports: $Exports<'electron-webpack/out/electron-main-hmr/HmrServer'>;
}
declare module 'electron-webpack/out/electron-main-hmr/main-hmr.js' {
  declare module.exports: $Exports<'electron-webpack/out/electron-main-hmr/main-hmr'>;
}
declare module 'electron-webpack/out/main.js' {
  declare module.exports: $Exports<'electron-webpack/out/main'>;
}
declare module 'electron-webpack/out/plugins/WatchMatchPlugin.js' {
  declare module.exports: $Exports<'electron-webpack/out/plugins/WatchMatchPlugin'>;
}
declare module 'electron-webpack/out/plugins/WebpackRemoveOldAssetsPlugin.js' {
  declare module.exports: $Exports<'electron-webpack/out/plugins/WebpackRemoveOldAssetsPlugin'>;
}
declare module 'electron-webpack/out/targets/BaseTarget.js' {
  declare module.exports: $Exports<'electron-webpack/out/targets/BaseTarget'>;
}
declare module 'electron-webpack/out/targets/MainTarget.js' {
  declare module.exports: $Exports<'electron-webpack/out/targets/MainTarget'>;
}
declare module 'electron-webpack/out/targets/RendererTarget.js' {
  declare module.exports: $Exports<'electron-webpack/out/targets/RendererTarget'>;
}
declare module 'electron-webpack/out/util.js' {
  declare module.exports: $Exports<'electron-webpack/out/util'>;
}
declare module 'electron-webpack/vue-renderer-entry.js' {
  declare module.exports: $Exports<'electron-webpack/vue-renderer-entry'>;
}
declare module 'electron-webpack/webpack.app.config.js' {
  declare module.exports: $Exports<'electron-webpack/webpack.app.config'>;
}
declare module 'electron-webpack/webpack.main.config.js' {
  declare module.exports: $Exports<'electron-webpack/webpack.main.config'>;
}
declare module 'electron-webpack/webpack.renderer.config.js' {
  declare module.exports: $Exports<'electron-webpack/webpack.renderer.config'>;
}
declare module 'electron-webpack/webpack.renderer.dll.config.js' {
  declare module.exports: $Exports<'electron-webpack/webpack.renderer.dll.config'>;
}
declare module 'electron-webpack/webpack.test.config.js' {
  declare module.exports: $Exports<'electron-webpack/webpack.test.config'>;
}
