// flow-typed signature: 33d904b96c8747ed8b41b631dd56dbab
// flow-typed version: <<STUB>>/keytar_v4.4.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'keytar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'keytar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'keytar/lib/keytar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'keytar/lib/keytar.js' {
  declare module.exports: $Exports<'keytar/lib/keytar'>;
}
