// flow-typed signature: abf6089d4460ac6456fc6aded78cc562
// flow-typed version: <<STUB>>/lbryinc_vlbryio/lbryinc#351d0a08806b0f770b50066b61a806171f6424d4/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lbryinc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lbryinc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lbryinc/dist/bundle' {
  declare module.exports: any;
}

declare module 'lbryinc/src/constants/action_types' {
  declare module.exports: any;
}

declare module 'lbryinc/src/constants/claim' {
  declare module.exports: any;
}

declare module 'lbryinc/src/constants/subscriptions' {
  declare module.exports: any;
}

declare module 'lbryinc/src/index' {
  declare module.exports: any;
}

declare module 'lbryinc/src/lbryio' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/actions/auth' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/actions/blacklist' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/actions/cost_info' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/actions/homepage' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/actions/rewards' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/actions/stats' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/actions/subscriptions' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/actions/user' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/reducers/auth' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/reducers/blacklist' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/reducers/cost_info' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/reducers/homepage' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/reducers/rewards' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/reducers/stats' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/reducers/subscriptions' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/reducers/user' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/selectors/auth' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/selectors/blacklist' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/selectors/cost_info' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/selectors/homepage' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/selectors/rewards' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/selectors/stats' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/selectors/subscriptions' {
  declare module.exports: any;
}

declare module 'lbryinc/src/redux/selectors/user' {
  declare module.exports: any;
}

declare module 'lbryinc/src/rewards' {
  declare module.exports: any;
}

declare module 'lbryinc/src/types/redux' {
  declare module.exports: any;
}

declare module 'lbryinc/src/types/subscription' {
  declare module.exports: any;
}

declare module 'lbryinc/src/util/redux-utils' {
  declare module.exports: any;
}

declare module 'lbryinc/src/util/swap-json' {
  declare module.exports: any;
}

declare module 'lbryinc/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lbryinc/dist/bundle.js' {
  declare module.exports: $Exports<'lbryinc/dist/bundle'>;
}
declare module 'lbryinc/src/constants/action_types.js' {
  declare module.exports: $Exports<'lbryinc/src/constants/action_types'>;
}
declare module 'lbryinc/src/constants/claim.js' {
  declare module.exports: $Exports<'lbryinc/src/constants/claim'>;
}
declare module 'lbryinc/src/constants/subscriptions.js' {
  declare module.exports: $Exports<'lbryinc/src/constants/subscriptions'>;
}
declare module 'lbryinc/src/index.js' {
  declare module.exports: $Exports<'lbryinc/src/index'>;
}
declare module 'lbryinc/src/lbryio.js' {
  declare module.exports: $Exports<'lbryinc/src/lbryio'>;
}
declare module 'lbryinc/src/redux/actions/auth.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/actions/auth'>;
}
declare module 'lbryinc/src/redux/actions/blacklist.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/actions/blacklist'>;
}
declare module 'lbryinc/src/redux/actions/cost_info.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/actions/cost_info'>;
}
declare module 'lbryinc/src/redux/actions/homepage.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/actions/homepage'>;
}
declare module 'lbryinc/src/redux/actions/rewards.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/actions/rewards'>;
}
declare module 'lbryinc/src/redux/actions/stats.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/actions/stats'>;
}
declare module 'lbryinc/src/redux/actions/subscriptions.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/actions/subscriptions'>;
}
declare module 'lbryinc/src/redux/actions/user.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/actions/user'>;
}
declare module 'lbryinc/src/redux/reducers/auth.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/reducers/auth'>;
}
declare module 'lbryinc/src/redux/reducers/blacklist.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/reducers/blacklist'>;
}
declare module 'lbryinc/src/redux/reducers/cost_info.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/reducers/cost_info'>;
}
declare module 'lbryinc/src/redux/reducers/homepage.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/reducers/homepage'>;
}
declare module 'lbryinc/src/redux/reducers/rewards.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/reducers/rewards'>;
}
declare module 'lbryinc/src/redux/reducers/stats.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/reducers/stats'>;
}
declare module 'lbryinc/src/redux/reducers/subscriptions.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/reducers/subscriptions'>;
}
declare module 'lbryinc/src/redux/reducers/user.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/reducers/user'>;
}
declare module 'lbryinc/src/redux/selectors/auth.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/selectors/auth'>;
}
declare module 'lbryinc/src/redux/selectors/blacklist.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/selectors/blacklist'>;
}
declare module 'lbryinc/src/redux/selectors/cost_info.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/selectors/cost_info'>;
}
declare module 'lbryinc/src/redux/selectors/homepage.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/selectors/homepage'>;
}
declare module 'lbryinc/src/redux/selectors/rewards.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/selectors/rewards'>;
}
declare module 'lbryinc/src/redux/selectors/stats.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/selectors/stats'>;
}
declare module 'lbryinc/src/redux/selectors/subscriptions.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/selectors/subscriptions'>;
}
declare module 'lbryinc/src/redux/selectors/user.js' {
  declare module.exports: $Exports<'lbryinc/src/redux/selectors/user'>;
}
declare module 'lbryinc/src/rewards.js' {
  declare module.exports: $Exports<'lbryinc/src/rewards'>;
}
declare module 'lbryinc/src/types/redux.js' {
  declare module.exports: $Exports<'lbryinc/src/types/redux'>;
}
declare module 'lbryinc/src/types/subscription.js' {
  declare module.exports: $Exports<'lbryinc/src/types/subscription'>;
}
declare module 'lbryinc/src/util/redux-utils.js' {
  declare module.exports: $Exports<'lbryinc/src/util/redux-utils'>;
}
declare module 'lbryinc/src/util/swap-json.js' {
  declare module.exports: $Exports<'lbryinc/src/util/swap-json'>;
}
declare module 'lbryinc/webpack.config.js' {
  declare module.exports: $Exports<'lbryinc/webpack.config'>;
}
