// flow-typed signature: d9df18e4d305eb10693693a45d09b0b9
// flow-typed version: <<STUB>>/lbry-format_vhttps://github.com/lbryio/lbry-format.git/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lbry-format'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lbry-format' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lbry-format/index' {
  declare module.exports: $Exports<'lbry-format'>;
}
declare module 'lbry-format/index.js' {
  declare module.exports: $Exports<'lbry-format'>;
}
