// flow-typed signature: 81f2c5c3e92d83856e8f389fc709eeb1
// flow-typed version: <<STUB>>/lbry-redux_vlbryio/lbry-redux#2a7e05940f892f104428eeb37bd1f178da811a09/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lbry-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lbry-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lbry-redux/dist/bundle' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/constants/action_types' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/constants/icons' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/constants/languages' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/constants/pages' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/constants/search' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/constants/settings' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/constants/shape_shift' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/constants/sort_options' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/constants/thumbnail_upload_statuses' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/constants/transaction_types' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/index' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/lbry' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/lbryURI' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/redux/actions/claims' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/redux/actions/file_info' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/redux/actions/notifications' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/redux/actions/search' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/redux/actions/wallet' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/redux/reducers/claims' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/redux/reducers/file_info' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/redux/reducers/notifications' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/redux/reducers/search' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/redux/reducers/wallet' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/redux/selectors/claims' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/redux/selectors/file_info' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/redux/selectors/navigation' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/redux/selectors/notifications' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/redux/selectors/search' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/redux/selectors/wallet' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/types/Notification' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/types/Search' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/util/batchActions' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/util/claim' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/util/debounce' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/util/formatCredits' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/util/handle-fetch' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/util/query_params' {
  declare module.exports: any;
}

declare module 'lbry-redux/src/util/redux-utils' {
  declare module.exports: any;
}

declare module 'lbry-redux/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lbry-redux/dist/bundle.js' {
  declare module.exports: $Exports<'lbry-redux/dist/bundle'>;
}
declare module 'lbry-redux/src/constants/action_types.js' {
  declare module.exports: $Exports<'lbry-redux/src/constants/action_types'>;
}
declare module 'lbry-redux/src/constants/icons.js' {
  declare module.exports: $Exports<'lbry-redux/src/constants/icons'>;
}
declare module 'lbry-redux/src/constants/languages.js' {
  declare module.exports: $Exports<'lbry-redux/src/constants/languages'>;
}
declare module 'lbry-redux/src/constants/pages.js' {
  declare module.exports: $Exports<'lbry-redux/src/constants/pages'>;
}
declare module 'lbry-redux/src/constants/search.js' {
  declare module.exports: $Exports<'lbry-redux/src/constants/search'>;
}
declare module 'lbry-redux/src/constants/settings.js' {
  declare module.exports: $Exports<'lbry-redux/src/constants/settings'>;
}
declare module 'lbry-redux/src/constants/shape_shift.js' {
  declare module.exports: $Exports<'lbry-redux/src/constants/shape_shift'>;
}
declare module 'lbry-redux/src/constants/sort_options.js' {
  declare module.exports: $Exports<'lbry-redux/src/constants/sort_options'>;
}
declare module 'lbry-redux/src/constants/thumbnail_upload_statuses.js' {
  declare module.exports: $Exports<'lbry-redux/src/constants/thumbnail_upload_statuses'>;
}
declare module 'lbry-redux/src/constants/transaction_types.js' {
  declare module.exports: $Exports<'lbry-redux/src/constants/transaction_types'>;
}
declare module 'lbry-redux/src/index.js' {
  declare module.exports: $Exports<'lbry-redux/src/index'>;
}
declare module 'lbry-redux/src/lbry.js' {
  declare module.exports: $Exports<'lbry-redux/src/lbry'>;
}
declare module 'lbry-redux/src/lbryURI.js' {
  declare module.exports: $Exports<'lbry-redux/src/lbryURI'>;
}
declare module 'lbry-redux/src/redux/actions/claims.js' {
  declare module.exports: $Exports<'lbry-redux/src/redux/actions/claims'>;
}
declare module 'lbry-redux/src/redux/actions/file_info.js' {
  declare module.exports: $Exports<'lbry-redux/src/redux/actions/file_info'>;
}
declare module 'lbry-redux/src/redux/actions/notifications.js' {
  declare module.exports: $Exports<'lbry-redux/src/redux/actions/notifications'>;
}
declare module 'lbry-redux/src/redux/actions/search.js' {
  declare module.exports: $Exports<'lbry-redux/src/redux/actions/search'>;
}
declare module 'lbry-redux/src/redux/actions/wallet.js' {
  declare module.exports: $Exports<'lbry-redux/src/redux/actions/wallet'>;
}
declare module 'lbry-redux/src/redux/reducers/claims.js' {
  declare module.exports: $Exports<'lbry-redux/src/redux/reducers/claims'>;
}
declare module 'lbry-redux/src/redux/reducers/file_info.js' {
  declare module.exports: $Exports<'lbry-redux/src/redux/reducers/file_info'>;
}
declare module 'lbry-redux/src/redux/reducers/notifications.js' {
  declare module.exports: $Exports<'lbry-redux/src/redux/reducers/notifications'>;
}
declare module 'lbry-redux/src/redux/reducers/search.js' {
  declare module.exports: $Exports<'lbry-redux/src/redux/reducers/search'>;
}
declare module 'lbry-redux/src/redux/reducers/wallet.js' {
  declare module.exports: $Exports<'lbry-redux/src/redux/reducers/wallet'>;
}
declare module 'lbry-redux/src/redux/selectors/claims.js' {
  declare module.exports: $Exports<'lbry-redux/src/redux/selectors/claims'>;
}
declare module 'lbry-redux/src/redux/selectors/file_info.js' {
  declare module.exports: $Exports<'lbry-redux/src/redux/selectors/file_info'>;
}
declare module 'lbry-redux/src/redux/selectors/navigation.js' {
  declare module.exports: $Exports<'lbry-redux/src/redux/selectors/navigation'>;
}
declare module 'lbry-redux/src/redux/selectors/notifications.js' {
  declare module.exports: $Exports<'lbry-redux/src/redux/selectors/notifications'>;
}
declare module 'lbry-redux/src/redux/selectors/search.js' {
  declare module.exports: $Exports<'lbry-redux/src/redux/selectors/search'>;
}
declare module 'lbry-redux/src/redux/selectors/wallet.js' {
  declare module.exports: $Exports<'lbry-redux/src/redux/selectors/wallet'>;
}
declare module 'lbry-redux/src/types/Notification.js' {
  declare module.exports: $Exports<'lbry-redux/src/types/Notification'>;
}
declare module 'lbry-redux/src/types/Search.js' {
  declare module.exports: $Exports<'lbry-redux/src/types/Search'>;
}
declare module 'lbry-redux/src/util/batchActions.js' {
  declare module.exports: $Exports<'lbry-redux/src/util/batchActions'>;
}
declare module 'lbry-redux/src/util/claim.js' {
  declare module.exports: $Exports<'lbry-redux/src/util/claim'>;
}
declare module 'lbry-redux/src/util/debounce.js' {
  declare module.exports: $Exports<'lbry-redux/src/util/debounce'>;
}
declare module 'lbry-redux/src/util/formatCredits.js' {
  declare module.exports: $Exports<'lbry-redux/src/util/formatCredits'>;
}
declare module 'lbry-redux/src/util/handle-fetch.js' {
  declare module.exports: $Exports<'lbry-redux/src/util/handle-fetch'>;
}
declare module 'lbry-redux/src/util/query_params.js' {
  declare module.exports: $Exports<'lbry-redux/src/util/query_params'>;
}
declare module 'lbry-redux/src/util/redux-utils.js' {
  declare module.exports: $Exports<'lbry-redux/src/util/redux-utils'>;
}
declare module 'lbry-redux/webpack.config.js' {
  declare module.exports: $Exports<'lbry-redux/webpack.config'>;
}
