// flow-typed signature: 951ee90843f8c063b5046f586d59e2cc
// flow-typed version: <<STUB>>/mammoth_v^1.4.6/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mammoth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mammoth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mammoth/browser/docx/files' {
  declare module.exports: any;
}

declare module 'mammoth/browser/unzip' {
  declare module.exports: any;
}

declare module 'mammoth/lib/document-to-html' {
  declare module.exports: any;
}

declare module 'mammoth/lib/documents' {
  declare module.exports: any;
}

declare module 'mammoth/lib/docx/body-reader' {
  declare module.exports: any;
}

declare module 'mammoth/lib/docx/comments-reader' {
  declare module.exports: any;
}

declare module 'mammoth/lib/docx/content-types-reader' {
  declare module.exports: any;
}

declare module 'mammoth/lib/docx/document-xml-reader' {
  declare module.exports: any;
}

declare module 'mammoth/lib/docx/docx-reader' {
  declare module.exports: any;
}

declare module 'mammoth/lib/docx/files' {
  declare module.exports: any;
}

declare module 'mammoth/lib/docx/notes-reader' {
  declare module.exports: any;
}

declare module 'mammoth/lib/docx/numbering-xml' {
  declare module.exports: any;
}

declare module 'mammoth/lib/docx/office-xml-reader' {
  declare module.exports: any;
}

declare module 'mammoth/lib/docx/relationships-reader' {
  declare module.exports: any;
}

declare module 'mammoth/lib/docx/style-map' {
  declare module.exports: any;
}

declare module 'mammoth/lib/docx/styles-reader' {
  declare module.exports: any;
}

declare module 'mammoth/lib/docx/uris' {
  declare module.exports: any;
}

declare module 'mammoth/lib/html/ast' {
  declare module.exports: any;
}

declare module 'mammoth/lib/html/index' {
  declare module.exports: any;
}

declare module 'mammoth/lib/html/simplify' {
  declare module.exports: any;
}

declare module 'mammoth/lib/images' {
  declare module.exports: any;
}

declare module 'mammoth/lib/index' {
  declare module.exports: any;
}

declare module 'mammoth/lib/main' {
  declare module.exports: any;
}

declare module 'mammoth/lib/options-reader' {
  declare module.exports: any;
}

declare module 'mammoth/lib/promises' {
  declare module.exports: any;
}

declare module 'mammoth/lib/results' {
  declare module.exports: any;
}

declare module 'mammoth/lib/style-reader' {
  declare module.exports: any;
}

declare module 'mammoth/lib/styles/document-matchers' {
  declare module.exports: any;
}

declare module 'mammoth/lib/styles/html-paths' {
  declare module.exports: any;
}

declare module 'mammoth/lib/styles/parser/tokeniser' {
  declare module.exports: any;
}

declare module 'mammoth/lib/transforms' {
  declare module.exports: any;
}

declare module 'mammoth/lib/underline' {
  declare module.exports: any;
}

declare module 'mammoth/lib/unzip' {
  declare module.exports: any;
}

declare module 'mammoth/lib/writers/html-writer' {
  declare module.exports: any;
}

declare module 'mammoth/lib/writers/index' {
  declare module.exports: any;
}

declare module 'mammoth/lib/writers/markdown-writer' {
  declare module.exports: any;
}

declare module 'mammoth/lib/xml/index' {
  declare module.exports: any;
}

declare module 'mammoth/lib/xml/nodes' {
  declare module.exports: any;
}

declare module 'mammoth/lib/xml/reader' {
  declare module.exports: any;
}

declare module 'mammoth/lib/xml/writer' {
  declare module.exports: any;
}

declare module 'mammoth/lib/zipfile' {
  declare module.exports: any;
}

declare module 'mammoth/mammoth.browser' {
  declare module.exports: any;
}

declare module 'mammoth/mammoth.browser.min' {
  declare module.exports: any;
}

declare module 'mammoth/test/document-to-html.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/docx/body-reader.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/docx/comments-reader.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/docx/content-types-reader.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/docx/document-matchers' {
  declare module.exports: any;
}

declare module 'mammoth/test/docx/docx-reader.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/docx/files.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/docx/notes-reader.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/docx/numbering-xml.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/docx/office-xml-reader.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/docx/relationships-reader.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/docx/style-map.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/docx/styles-reader.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/docx/uris.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/html/simplify.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/html/write.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/images.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/main.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/mammoth.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/options-reader.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/results.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/style-reader.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/styles/document-matchers.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/styles/html-paths.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/styles/parser/tokeniser.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/test' {
  declare module.exports: any;
}

declare module 'mammoth/test/testing' {
  declare module.exports: any;
}

declare module 'mammoth/test/transforms.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/unzip.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/writers/html-writer.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/writers/markdown-writer.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/xml/reader.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/xml/writer.tests' {
  declare module.exports: any;
}

declare module 'mammoth/test/zipfile.tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mammoth/browser/docx/files.js' {
  declare module.exports: $Exports<'mammoth/browser/docx/files'>;
}
declare module 'mammoth/browser/unzip.js' {
  declare module.exports: $Exports<'mammoth/browser/unzip'>;
}
declare module 'mammoth/lib/document-to-html.js' {
  declare module.exports: $Exports<'mammoth/lib/document-to-html'>;
}
declare module 'mammoth/lib/documents.js' {
  declare module.exports: $Exports<'mammoth/lib/documents'>;
}
declare module 'mammoth/lib/docx/body-reader.js' {
  declare module.exports: $Exports<'mammoth/lib/docx/body-reader'>;
}
declare module 'mammoth/lib/docx/comments-reader.js' {
  declare module.exports: $Exports<'mammoth/lib/docx/comments-reader'>;
}
declare module 'mammoth/lib/docx/content-types-reader.js' {
  declare module.exports: $Exports<'mammoth/lib/docx/content-types-reader'>;
}
declare module 'mammoth/lib/docx/document-xml-reader.js' {
  declare module.exports: $Exports<'mammoth/lib/docx/document-xml-reader'>;
}
declare module 'mammoth/lib/docx/docx-reader.js' {
  declare module.exports: $Exports<'mammoth/lib/docx/docx-reader'>;
}
declare module 'mammoth/lib/docx/files.js' {
  declare module.exports: $Exports<'mammoth/lib/docx/files'>;
}
declare module 'mammoth/lib/docx/notes-reader.js' {
  declare module.exports: $Exports<'mammoth/lib/docx/notes-reader'>;
}
declare module 'mammoth/lib/docx/numbering-xml.js' {
  declare module.exports: $Exports<'mammoth/lib/docx/numbering-xml'>;
}
declare module 'mammoth/lib/docx/office-xml-reader.js' {
  declare module.exports: $Exports<'mammoth/lib/docx/office-xml-reader'>;
}
declare module 'mammoth/lib/docx/relationships-reader.js' {
  declare module.exports: $Exports<'mammoth/lib/docx/relationships-reader'>;
}
declare module 'mammoth/lib/docx/style-map.js' {
  declare module.exports: $Exports<'mammoth/lib/docx/style-map'>;
}
declare module 'mammoth/lib/docx/styles-reader.js' {
  declare module.exports: $Exports<'mammoth/lib/docx/styles-reader'>;
}
declare module 'mammoth/lib/docx/uris.js' {
  declare module.exports: $Exports<'mammoth/lib/docx/uris'>;
}
declare module 'mammoth/lib/html/ast.js' {
  declare module.exports: $Exports<'mammoth/lib/html/ast'>;
}
declare module 'mammoth/lib/html/index.js' {
  declare module.exports: $Exports<'mammoth/lib/html/index'>;
}
declare module 'mammoth/lib/html/simplify.js' {
  declare module.exports: $Exports<'mammoth/lib/html/simplify'>;
}
declare module 'mammoth/lib/images.js' {
  declare module.exports: $Exports<'mammoth/lib/images'>;
}
declare module 'mammoth/lib/index.js' {
  declare module.exports: $Exports<'mammoth/lib/index'>;
}
declare module 'mammoth/lib/main.js' {
  declare module.exports: $Exports<'mammoth/lib/main'>;
}
declare module 'mammoth/lib/options-reader.js' {
  declare module.exports: $Exports<'mammoth/lib/options-reader'>;
}
declare module 'mammoth/lib/promises.js' {
  declare module.exports: $Exports<'mammoth/lib/promises'>;
}
declare module 'mammoth/lib/results.js' {
  declare module.exports: $Exports<'mammoth/lib/results'>;
}
declare module 'mammoth/lib/style-reader.js' {
  declare module.exports: $Exports<'mammoth/lib/style-reader'>;
}
declare module 'mammoth/lib/styles/document-matchers.js' {
  declare module.exports: $Exports<'mammoth/lib/styles/document-matchers'>;
}
declare module 'mammoth/lib/styles/html-paths.js' {
  declare module.exports: $Exports<'mammoth/lib/styles/html-paths'>;
}
declare module 'mammoth/lib/styles/parser/tokeniser.js' {
  declare module.exports: $Exports<'mammoth/lib/styles/parser/tokeniser'>;
}
declare module 'mammoth/lib/transforms.js' {
  declare module.exports: $Exports<'mammoth/lib/transforms'>;
}
declare module 'mammoth/lib/underline.js' {
  declare module.exports: $Exports<'mammoth/lib/underline'>;
}
declare module 'mammoth/lib/unzip.js' {
  declare module.exports: $Exports<'mammoth/lib/unzip'>;
}
declare module 'mammoth/lib/writers/html-writer.js' {
  declare module.exports: $Exports<'mammoth/lib/writers/html-writer'>;
}
declare module 'mammoth/lib/writers/index.js' {
  declare module.exports: $Exports<'mammoth/lib/writers/index'>;
}
declare module 'mammoth/lib/writers/markdown-writer.js' {
  declare module.exports: $Exports<'mammoth/lib/writers/markdown-writer'>;
}
declare module 'mammoth/lib/xml/index.js' {
  declare module.exports: $Exports<'mammoth/lib/xml/index'>;
}
declare module 'mammoth/lib/xml/nodes.js' {
  declare module.exports: $Exports<'mammoth/lib/xml/nodes'>;
}
declare module 'mammoth/lib/xml/reader.js' {
  declare module.exports: $Exports<'mammoth/lib/xml/reader'>;
}
declare module 'mammoth/lib/xml/writer.js' {
  declare module.exports: $Exports<'mammoth/lib/xml/writer'>;
}
declare module 'mammoth/lib/zipfile.js' {
  declare module.exports: $Exports<'mammoth/lib/zipfile'>;
}
declare module 'mammoth/mammoth.browser.js' {
  declare module.exports: $Exports<'mammoth/mammoth.browser'>;
}
declare module 'mammoth/mammoth.browser.min.js' {
  declare module.exports: $Exports<'mammoth/mammoth.browser.min'>;
}
declare module 'mammoth/test/document-to-html.tests.js' {
  declare module.exports: $Exports<'mammoth/test/document-to-html.tests'>;
}
declare module 'mammoth/test/docx/body-reader.tests.js' {
  declare module.exports: $Exports<'mammoth/test/docx/body-reader.tests'>;
}
declare module 'mammoth/test/docx/comments-reader.tests.js' {
  declare module.exports: $Exports<'mammoth/test/docx/comments-reader.tests'>;
}
declare module 'mammoth/test/docx/content-types-reader.tests.js' {
  declare module.exports: $Exports<'mammoth/test/docx/content-types-reader.tests'>;
}
declare module 'mammoth/test/docx/document-matchers.js' {
  declare module.exports: $Exports<'mammoth/test/docx/document-matchers'>;
}
declare module 'mammoth/test/docx/docx-reader.tests.js' {
  declare module.exports: $Exports<'mammoth/test/docx/docx-reader.tests'>;
}
declare module 'mammoth/test/docx/files.tests.js' {
  declare module.exports: $Exports<'mammoth/test/docx/files.tests'>;
}
declare module 'mammoth/test/docx/notes-reader.tests.js' {
  declare module.exports: $Exports<'mammoth/test/docx/notes-reader.tests'>;
}
declare module 'mammoth/test/docx/numbering-xml.tests.js' {
  declare module.exports: $Exports<'mammoth/test/docx/numbering-xml.tests'>;
}
declare module 'mammoth/test/docx/office-xml-reader.tests.js' {
  declare module.exports: $Exports<'mammoth/test/docx/office-xml-reader.tests'>;
}
declare module 'mammoth/test/docx/relationships-reader.tests.js' {
  declare module.exports: $Exports<'mammoth/test/docx/relationships-reader.tests'>;
}
declare module 'mammoth/test/docx/style-map.tests.js' {
  declare module.exports: $Exports<'mammoth/test/docx/style-map.tests'>;
}
declare module 'mammoth/test/docx/styles-reader.tests.js' {
  declare module.exports: $Exports<'mammoth/test/docx/styles-reader.tests'>;
}
declare module 'mammoth/test/docx/uris.tests.js' {
  declare module.exports: $Exports<'mammoth/test/docx/uris.tests'>;
}
declare module 'mammoth/test/html/simplify.tests.js' {
  declare module.exports: $Exports<'mammoth/test/html/simplify.tests'>;
}
declare module 'mammoth/test/html/write.tests.js' {
  declare module.exports: $Exports<'mammoth/test/html/write.tests'>;
}
declare module 'mammoth/test/images.tests.js' {
  declare module.exports: $Exports<'mammoth/test/images.tests'>;
}
declare module 'mammoth/test/main.tests.js' {
  declare module.exports: $Exports<'mammoth/test/main.tests'>;
}
declare module 'mammoth/test/mammoth.tests.js' {
  declare module.exports: $Exports<'mammoth/test/mammoth.tests'>;
}
declare module 'mammoth/test/options-reader.tests.js' {
  declare module.exports: $Exports<'mammoth/test/options-reader.tests'>;
}
declare module 'mammoth/test/results.tests.js' {
  declare module.exports: $Exports<'mammoth/test/results.tests'>;
}
declare module 'mammoth/test/style-reader.tests.js' {
  declare module.exports: $Exports<'mammoth/test/style-reader.tests'>;
}
declare module 'mammoth/test/styles/document-matchers.tests.js' {
  declare module.exports: $Exports<'mammoth/test/styles/document-matchers.tests'>;
}
declare module 'mammoth/test/styles/html-paths.tests.js' {
  declare module.exports: $Exports<'mammoth/test/styles/html-paths.tests'>;
}
declare module 'mammoth/test/styles/parser/tokeniser.tests.js' {
  declare module.exports: $Exports<'mammoth/test/styles/parser/tokeniser.tests'>;
}
declare module 'mammoth/test/test.js' {
  declare module.exports: $Exports<'mammoth/test/test'>;
}
declare module 'mammoth/test/testing.js' {
  declare module.exports: $Exports<'mammoth/test/testing'>;
}
declare module 'mammoth/test/transforms.tests.js' {
  declare module.exports: $Exports<'mammoth/test/transforms.tests'>;
}
declare module 'mammoth/test/unzip.tests.js' {
  declare module.exports: $Exports<'mammoth/test/unzip.tests'>;
}
declare module 'mammoth/test/writers/html-writer.tests.js' {
  declare module.exports: $Exports<'mammoth/test/writers/html-writer.tests'>;
}
declare module 'mammoth/test/writers/markdown-writer.tests.js' {
  declare module.exports: $Exports<'mammoth/test/writers/markdown-writer.tests'>;
}
declare module 'mammoth/test/xml/reader.tests.js' {
  declare module.exports: $Exports<'mammoth/test/xml/reader.tests'>;
}
declare module 'mammoth/test/xml/writer.tests.js' {
  declare module.exports: $Exports<'mammoth/test/xml/writer.tests'>;
}
declare module 'mammoth/test/zipfile.tests.js' {
  declare module.exports: $Exports<'mammoth/test/zipfile.tests'>;
}
