// flow-typed signature: a3e5dd3c1b956fb8248d1138e633b09d
// flow-typed version: <<STUB>>/node-abi_v^2.5.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-abi'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-abi' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-abi/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-abi/index' {
  declare module.exports: $Exports<'node-abi'>;
}
declare module 'node-abi/index.js' {
  declare module.exports: $Exports<'node-abi'>;
}
declare module 'node-abi/test/index.js' {
  declare module.exports: $Exports<'node-abi/test/index'>;
}
