// flow-typed signature: 2814a9bd926cb80bbec0ca881e0a7933
// flow-typed version: <<STUB>>/node-loader_v^0.6.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'node-loader/index' {
  declare module.exports: $Exports<'node-loader'>;
}
declare module 'node-loader/index.js' {
  declare module.exports: $Exports<'node-loader'>;
}
