// flow-typed signature: eb8f21fe856507a71c375619b81870ca
// flow-typed version: <<STUB>>/preprocess-loader_v^0.3.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preprocess-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preprocess-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preprocess-loader/test/src/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preprocess-loader/index' {
  declare module.exports: $Exports<'preprocess-loader'>;
}
declare module 'preprocess-loader/index.js' {
  declare module.exports: $Exports<'preprocess-loader'>;
}
declare module 'preprocess-loader/test/src/test.js' {
  declare module.exports: $Exports<'preprocess-loader/test/src/test'>;
}
