// flow-typed signature: 2ff2dd5c6603f96006d4765eb2218dd7
// flow-typed version: <<STUB>>/rc-progress_v^2.0.6/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-progress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-progress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-progress/dist/rc-progress' {
  declare module.exports: any;
}

declare module 'rc-progress/dist/rc-progress.min' {
  declare module.exports: any;
}

declare module 'rc-progress/es/Circle' {
  declare module.exports: any;
}

declare module 'rc-progress/es/enhancer' {
  declare module.exports: any;
}

declare module 'rc-progress/es/index' {
  declare module.exports: any;
}

declare module 'rc-progress/es/Line' {
  declare module.exports: any;
}

declare module 'rc-progress/es/types' {
  declare module.exports: any;
}

declare module 'rc-progress/lib/Circle' {
  declare module.exports: any;
}

declare module 'rc-progress/lib/enhancer' {
  declare module.exports: any;
}

declare module 'rc-progress/lib/index' {
  declare module.exports: any;
}

declare module 'rc-progress/lib/Line' {
  declare module.exports: any;
}

declare module 'rc-progress/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-progress/dist/rc-progress.js' {
  declare module.exports: $Exports<'rc-progress/dist/rc-progress'>;
}
declare module 'rc-progress/dist/rc-progress.min.js' {
  declare module.exports: $Exports<'rc-progress/dist/rc-progress.min'>;
}
declare module 'rc-progress/es/Circle.js' {
  declare module.exports: $Exports<'rc-progress/es/Circle'>;
}
declare module 'rc-progress/es/enhancer.js' {
  declare module.exports: $Exports<'rc-progress/es/enhancer'>;
}
declare module 'rc-progress/es/index.js' {
  declare module.exports: $Exports<'rc-progress/es/index'>;
}
declare module 'rc-progress/es/Line.js' {
  declare module.exports: $Exports<'rc-progress/es/Line'>;
}
declare module 'rc-progress/es/types.js' {
  declare module.exports: $Exports<'rc-progress/es/types'>;
}
declare module 'rc-progress/lib/Circle.js' {
  declare module.exports: $Exports<'rc-progress/lib/Circle'>;
}
declare module 'rc-progress/lib/enhancer.js' {
  declare module.exports: $Exports<'rc-progress/lib/enhancer'>;
}
declare module 'rc-progress/lib/index.js' {
  declare module.exports: $Exports<'rc-progress/lib/index'>;
}
declare module 'rc-progress/lib/Line.js' {
  declare module.exports: $Exports<'rc-progress/lib/Line'>;
}
declare module 'rc-progress/lib/types.js' {
  declare module.exports: $Exports<'rc-progress/lib/types'>;
}
