// flow-typed signature: 33f995e7f7c2a09f6b3d3c10a6d50eb3
// flow-typed version: <<STUB>>/react-paginate_v^5.2.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-paginate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-paginate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-paginate/__tests__/PaginationBoxView-test' {
  declare module.exports: any;
}

declare module 'react-paginate/demo/data' {
  declare module.exports: any;
}

declare module 'react-paginate/demo/js/demo' {
  declare module.exports: any;
}

declare module 'react-paginate/demo/server' {
  declare module.exports: any;
}

declare module 'react-paginate/demo/webpack.config' {
  declare module.exports: any;
}

declare module 'react-paginate/dist/BreakView' {
  declare module.exports: any;
}

declare module 'react-paginate/dist/index' {
  declare module.exports: any;
}

declare module 'react-paginate/dist/PageView' {
  declare module.exports: any;
}

declare module 'react-paginate/dist/PaginationBoxView' {
  declare module.exports: any;
}

declare module 'react-paginate/react_components/BreakView' {
  declare module.exports: any;
}

declare module 'react-paginate/react_components/index' {
  declare module.exports: any;
}

declare module 'react-paginate/react_components/PageView' {
  declare module.exports: any;
}

declare module 'react-paginate/react_components/PaginationBoxView' {
  declare module.exports: any;
}

declare module 'react-paginate/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-paginate/__tests__/PaginationBoxView-test.js' {
  declare module.exports: $Exports<'react-paginate/__tests__/PaginationBoxView-test'>;
}
declare module 'react-paginate/demo/data.js' {
  declare module.exports: $Exports<'react-paginate/demo/data'>;
}
declare module 'react-paginate/demo/js/demo.js' {
  declare module.exports: $Exports<'react-paginate/demo/js/demo'>;
}
declare module 'react-paginate/demo/server.js' {
  declare module.exports: $Exports<'react-paginate/demo/server'>;
}
declare module 'react-paginate/demo/webpack.config.js' {
  declare module.exports: $Exports<'react-paginate/demo/webpack.config'>;
}
declare module 'react-paginate/dist/BreakView.js' {
  declare module.exports: $Exports<'react-paginate/dist/BreakView'>;
}
declare module 'react-paginate/dist/index.js' {
  declare module.exports: $Exports<'react-paginate/dist/index'>;
}
declare module 'react-paginate/dist/PageView.js' {
  declare module.exports: $Exports<'react-paginate/dist/PageView'>;
}
declare module 'react-paginate/dist/PaginationBoxView.js' {
  declare module.exports: $Exports<'react-paginate/dist/PaginationBoxView'>;
}
declare module 'react-paginate/react_components/BreakView.js' {
  declare module.exports: $Exports<'react-paginate/react_components/BreakView'>;
}
declare module 'react-paginate/react_components/index.js' {
  declare module.exports: $Exports<'react-paginate/react_components/index'>;
}
declare module 'react-paginate/react_components/PageView.js' {
  declare module.exports: $Exports<'react-paginate/react_components/PageView'>;
}
declare module 'react-paginate/react_components/PaginationBoxView.js' {
  declare module.exports: $Exports<'react-paginate/react_components/PaginationBoxView'>;
}
declare module 'react-paginate/webpack.config.js' {
  declare module.exports: $Exports<'react-paginate/webpack.config'>;
}
