// flow-typed signature: e608b918ca89e893d099bea25ba2d0ba
// flow-typed version: <<STUB>>/react-simplemde-editor_v^4.0.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-simplemde-editor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-simplemde-editor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-simplemde-editor/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-simplemde-editor/lib/index.js' {
  declare module.exports: $Exports<'react-simplemde-editor/lib/index'>;
}
