// flow-typed signature: f7dc2de16b8e348445c2ef944161d898
// flow-typed version: <<STUB>>/remark-react_v^4.0.3/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-react/index' {
  declare module.exports: $Exports<'remark-react'>;
}
declare module 'remark-react/index.js' {
  declare module.exports: $Exports<'remark-react'>;
}
