// flow-typed signature: 7053080a28c70b71438b00858def6be0
// flow-typed version: <<STUB>>/render-media_v^3.1.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'render-media'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'render-media' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'render-media/index' {
  declare module.exports: $Exports<'render-media'>;
}
declare module 'render-media/index.js' {
  declare module.exports: $Exports<'render-media'>;
}
