// flow-typed signature: c0c09b83d9159e7a6e2bbc7eb089e42f
// flow-typed version: <<STUB>>/stream-to-blob-url_v^2.1.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stream-to-blob-url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stream-to-blob-url' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stream-to-blob-url/index' {
  declare module.exports: $Exports<'stream-to-blob-url'>;
}
declare module 'stream-to-blob-url/index.js' {
  declare module.exports: $Exports<'stream-to-blob-url'>;
}
