// flow-typed signature: 119b891fded3f6f769118c64c0924aa8
// flow-typed version: <<STUB>>/webpack-config-utils_v^2.3.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-config-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-config-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-config-utils/dist/get-if-utils' {
  declare module.exports: any;
}

declare module 'webpack-config-utils/dist/index' {
  declare module.exports: any;
}

declare module 'webpack-config-utils/dist/prop-if' {
  declare module.exports: any;
}

declare module 'webpack-config-utils/dist/remove-empty' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-config-utils/dist/get-if-utils.js' {
  declare module.exports: $Exports<'webpack-config-utils/dist/get-if-utils'>;
}
declare module 'webpack-config-utils/dist/index.js' {
  declare module.exports: $Exports<'webpack-config-utils/dist/index'>;
}
declare module 'webpack-config-utils/dist/prop-if.js' {
  declare module.exports: $Exports<'webpack-config-utils/dist/prop-if'>;
}
declare module 'webpack-config-utils/dist/remove-empty.js' {
  declare module.exports: $Exports<'webpack-config-utils/dist/remove-empty'>;
}
