// flow-typed signature: e698725e48931b3fdcf612e52bf5cbee
// flow-typed version: <<STUB>>/webpack-dev-server_v^3.1.14/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-dev-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-dev-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-dev-server/bin/options' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/bin/webpack-dev-server' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/index.bundle' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/index' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/live.bundle' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/overlay' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/socket' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/sockjs.bundle' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/client/webpack.config' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/Server' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/addEntries' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/colors' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/createCertificate' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/createConfig' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/createDomain' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/createLogger' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/defaultTo' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/getVersions' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/runBonjour' {
  declare module.exports: any;
}

declare module 'webpack-dev-server/lib/utils/status' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-dev-server/bin/options.js' {
  declare module.exports: $Exports<'webpack-dev-server/bin/options'>;
}
declare module 'webpack-dev-server/bin/webpack-dev-server.js' {
  declare module.exports: $Exports<'webpack-dev-server/bin/webpack-dev-server'>;
}
declare module 'webpack-dev-server/client/index.bundle.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/index.bundle'>;
}
declare module 'webpack-dev-server/client/index.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/index'>;
}
declare module 'webpack-dev-server/client/live.bundle.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/live.bundle'>;
}
declare module 'webpack-dev-server/client/overlay.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/overlay'>;
}
declare module 'webpack-dev-server/client/socket.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/socket'>;
}
declare module 'webpack-dev-server/client/sockjs.bundle.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/sockjs.bundle'>;
}
declare module 'webpack-dev-server/client/webpack.config.js' {
  declare module.exports: $Exports<'webpack-dev-server/client/webpack.config'>;
}
declare module 'webpack-dev-server/lib/Server.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/Server'>;
}
declare module 'webpack-dev-server/lib/utils/addEntries.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/addEntries'>;
}
declare module 'webpack-dev-server/lib/utils/colors.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/colors'>;
}
declare module 'webpack-dev-server/lib/utils/createCertificate.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/createCertificate'>;
}
declare module 'webpack-dev-server/lib/utils/createConfig.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/createConfig'>;
}
declare module 'webpack-dev-server/lib/utils/createDomain.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/createDomain'>;
}
declare module 'webpack-dev-server/lib/utils/createLogger.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/createLogger'>;
}
declare module 'webpack-dev-server/lib/utils/defaultTo.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/defaultTo'>;
}
declare module 'webpack-dev-server/lib/utils/getVersions.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/getVersions'>;
}
declare module 'webpack-dev-server/lib/utils/runBonjour.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/runBonjour'>;
}
declare module 'webpack-dev-server/lib/utils/status.js' {
  declare module.exports: $Exports<'webpack-dev-server/lib/utils/status'>;
}
