// flow-typed signature: af76d3115110c79081ef77256aed7826
// flow-typed version: <<STUB>>/webpack-merge_v^4.2.1/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-merge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-merge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-merge/lib/index' {
  declare module.exports: any;
}

declare module 'webpack-merge/lib/join-arrays-smart' {
  declare module.exports: any;
}

declare module 'webpack-merge/lib/join-arrays' {
  declare module.exports: any;
}

declare module 'webpack-merge/lib/types' {
  declare module.exports: any;
}

declare module 'webpack-merge/lib/unique' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-merge/lib/index.js' {
  declare module.exports: $Exports<'webpack-merge/lib/index'>;
}
declare module 'webpack-merge/lib/join-arrays-smart.js' {
  declare module.exports: $Exports<'webpack-merge/lib/join-arrays-smart'>;
}
declare module 'webpack-merge/lib/join-arrays.js' {
  declare module.exports: $Exports<'webpack-merge/lib/join-arrays'>;
}
declare module 'webpack-merge/lib/types.js' {
  declare module.exports: $Exports<'webpack-merge/lib/types'>;
}
declare module 'webpack-merge/lib/unique.js' {
  declare module.exports: $Exports<'webpack-merge/lib/unique'>;
}
