// flow-typed signature: b5fa2ddf719133674597b9d1726b5201
// flow-typed version: <<STUB>>/y18n_v^4.0.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'y18n'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'y18n' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'y18n/index' {
  declare module.exports: $Exports<'y18n'>;
}
declare module 'y18n/index.js' {
  declare module.exports: $Exports<'y18n'>;
}
