// flow-typed signature: 79434e2f5428e83cfb069a737be1d8eb
// flow-typed version: <<STUB>>/yarnhook_v^0.2.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yarnhook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yarnhook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'yarnhook/index' {
  declare module.exports: $Exports<'yarnhook'>;
}
declare module 'yarnhook/index.js' {
  declare module.exports: $Exports<'yarnhook'>;
}
