// flow-typed signature: 3213370d53d43337e039b1f99b90ad98
// flow-typed version: <<STUB>>/@lbry/color_v^1.0.2/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lbry/color'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@lbry/color' {
  declare module.exports: any;
}
