// flow-typed signature: 8b77537ae4d6c835866e04a70a0ad6f3
// flow-typed version: <<STUB>>/@lbry/components_v^2.2.4/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lbry/components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@lbry/components' {
  declare module.exports: any;
}
