// flow-typed signature: 7025e1d060874c9ed272b10b43d6cbd4
// flow-typed version: <<STUB>>/@hot-loader/react-dom_v16.8/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@hot-loader/react-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@hot-loader/react-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@hot-loader/react-dom/cjs/react-dom-server.browser.development' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/cjs/react-dom-server.browser.production.min' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/cjs/react-dom-server.node.development' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/cjs/react-dom-server.node.production.min' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/cjs/react-dom-test-utils.development' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/cjs/react-dom-test-utils.production.min' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/cjs/react-dom-unstable-fire.development' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/cjs/react-dom-unstable-fire.production.min' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/cjs/react-dom-unstable-fire.profiling.min' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/cjs/react-dom-unstable-fizz.browser.development' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/cjs/react-dom-unstable-fizz.browser.production.min' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/cjs/react-dom-unstable-fizz.node.development' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/cjs/react-dom-unstable-fizz.node.production.min' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/cjs/react-dom-unstable-native-dependencies.development' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/cjs/react-dom-unstable-native-dependencies.production.min' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/cjs/react-dom.development' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/cjs/react-dom.production.min' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/cjs/react-dom.profiling.min' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/profiling' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/server.browser' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/server' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/server.node' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/test-utils' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/umd/react-dom-server.browser.development' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/umd/react-dom-server.browser.production.min' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/umd/react-dom-test-utils.development' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/umd/react-dom-test-utils.production.min' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/umd/react-dom-unstable-fire.development' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/umd/react-dom-unstable-fire.production.min' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/umd/react-dom-unstable-fire.profiling.min' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/umd/react-dom-unstable-fizz.browser.development' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/umd/react-dom-unstable-fizz.browser.production.min' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/umd/react-dom-unstable-native-dependencies.development' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/umd/react-dom-unstable-native-dependencies.production.min' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/umd/react-dom.development' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/umd/react-dom.production.min' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/umd/react-dom.profiling.min' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/unstable-fizz.browser' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/unstable-fizz' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/unstable-fizz.node' {
  declare module.exports: any;
}

declare module '@hot-loader/react-dom/unstable-native-dependencies' {
  declare module.exports: any;
}

// Filename aliases
declare module '@hot-loader/react-dom/cjs/react-dom-server.browser.development.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/cjs/react-dom-server.browser.development'>;
}
declare module '@hot-loader/react-dom/cjs/react-dom-server.browser.production.min.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/cjs/react-dom-server.browser.production.min'>;
}
declare module '@hot-loader/react-dom/cjs/react-dom-server.node.development.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/cjs/react-dom-server.node.development'>;
}
declare module '@hot-loader/react-dom/cjs/react-dom-server.node.production.min.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/cjs/react-dom-server.node.production.min'>;
}
declare module '@hot-loader/react-dom/cjs/react-dom-test-utils.development.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/cjs/react-dom-test-utils.development'>;
}
declare module '@hot-loader/react-dom/cjs/react-dom-test-utils.production.min.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/cjs/react-dom-test-utils.production.min'>;
}
declare module '@hot-loader/react-dom/cjs/react-dom-unstable-fire.development.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/cjs/react-dom-unstable-fire.development'>;
}
declare module '@hot-loader/react-dom/cjs/react-dom-unstable-fire.production.min.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/cjs/react-dom-unstable-fire.production.min'>;
}
declare module '@hot-loader/react-dom/cjs/react-dom-unstable-fire.profiling.min.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/cjs/react-dom-unstable-fire.profiling.min'>;
}
declare module '@hot-loader/react-dom/cjs/react-dom-unstable-fizz.browser.development.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/cjs/react-dom-unstable-fizz.browser.development'>;
}
declare module '@hot-loader/react-dom/cjs/react-dom-unstable-fizz.browser.production.min.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/cjs/react-dom-unstable-fizz.browser.production.min'>;
}
declare module '@hot-loader/react-dom/cjs/react-dom-unstable-fizz.node.development.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/cjs/react-dom-unstable-fizz.node.development'>;
}
declare module '@hot-loader/react-dom/cjs/react-dom-unstable-fizz.node.production.min.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/cjs/react-dom-unstable-fizz.node.production.min'>;
}
declare module '@hot-loader/react-dom/cjs/react-dom-unstable-native-dependencies.development.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/cjs/react-dom-unstable-native-dependencies.development'>;
}
declare module '@hot-loader/react-dom/cjs/react-dom-unstable-native-dependencies.production.min.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/cjs/react-dom-unstable-native-dependencies.production.min'>;
}
declare module '@hot-loader/react-dom/cjs/react-dom.development.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/cjs/react-dom.development'>;
}
declare module '@hot-loader/react-dom/cjs/react-dom.production.min.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/cjs/react-dom.production.min'>;
}
declare module '@hot-loader/react-dom/cjs/react-dom.profiling.min.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/cjs/react-dom.profiling.min'>;
}
declare module '@hot-loader/react-dom/index' {
  declare module.exports: $Exports<'@hot-loader/react-dom'>;
}
declare module '@hot-loader/react-dom/index.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom'>;
}
declare module '@hot-loader/react-dom/profiling.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/profiling'>;
}
declare module '@hot-loader/react-dom/server.browser.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/server.browser'>;
}
declare module '@hot-loader/react-dom/server.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/server'>;
}
declare module '@hot-loader/react-dom/server.node.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/server.node'>;
}
declare module '@hot-loader/react-dom/test-utils.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/test-utils'>;
}
declare module '@hot-loader/react-dom/umd/react-dom-server.browser.development.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/umd/react-dom-server.browser.development'>;
}
declare module '@hot-loader/react-dom/umd/react-dom-server.browser.production.min.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/umd/react-dom-server.browser.production.min'>;
}
declare module '@hot-loader/react-dom/umd/react-dom-test-utils.development.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/umd/react-dom-test-utils.development'>;
}
declare module '@hot-loader/react-dom/umd/react-dom-test-utils.production.min.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/umd/react-dom-test-utils.production.min'>;
}
declare module '@hot-loader/react-dom/umd/react-dom-unstable-fire.development.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/umd/react-dom-unstable-fire.development'>;
}
declare module '@hot-loader/react-dom/umd/react-dom-unstable-fire.production.min.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/umd/react-dom-unstable-fire.production.min'>;
}
declare module '@hot-loader/react-dom/umd/react-dom-unstable-fire.profiling.min.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/umd/react-dom-unstable-fire.profiling.min'>;
}
declare module '@hot-loader/react-dom/umd/react-dom-unstable-fizz.browser.development.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/umd/react-dom-unstable-fizz.browser.development'>;
}
declare module '@hot-loader/react-dom/umd/react-dom-unstable-fizz.browser.production.min.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/umd/react-dom-unstable-fizz.browser.production.min'>;
}
declare module '@hot-loader/react-dom/umd/react-dom-unstable-native-dependencies.development.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/umd/react-dom-unstable-native-dependencies.development'>;
}
declare module '@hot-loader/react-dom/umd/react-dom-unstable-native-dependencies.production.min.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/umd/react-dom-unstable-native-dependencies.production.min'>;
}
declare module '@hot-loader/react-dom/umd/react-dom.development.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/umd/react-dom.development'>;
}
declare module '@hot-loader/react-dom/umd/react-dom.production.min.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/umd/react-dom.production.min'>;
}
declare module '@hot-loader/react-dom/umd/react-dom.profiling.min.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/umd/react-dom.profiling.min'>;
}
declare module '@hot-loader/react-dom/unstable-fizz.browser.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/unstable-fizz.browser'>;
}
declare module '@hot-loader/react-dom/unstable-fizz.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/unstable-fizz'>;
}
declare module '@hot-loader/react-dom/unstable-fizz.node.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/unstable-fizz.node'>;
}
declare module '@hot-loader/react-dom/unstable-native-dependencies.js' {
  declare module.exports: $Exports<'@hot-loader/react-dom/unstable-native-dependencies'>;
}
